### PR TITLE
add types for descriptor and manifest

### PR DESCRIPTION
**Pull request by mengqiy**
We finally agreed to land on kubectl repo.
Moved from main repo PR: https://github.com/kubernetes/kubernetes/pull/52570.
A lot of discussion there.

### CODE REVIEW

**Comment by mengqiy** [comment]
cc: @bgrant0607-cc PTAL

**Comment by bgrant0607** [comment]
Thanks. 

I'm currently thinking we should break out Descriptor into a CRD definition somewhere (possibly not in this repo) and put a reference in Manifest to an "owner". Kubectl could then set ownerReferences to the owner automatically. The owner could be the Descriptor CRD or another object. Kubectl doesn't actually need the Descriptor for anything during expansion.

But further changes can be made in subsequent PRs. Merge and iterate.

/lgtm

**Comment by bgrant0607** [comment]
A followup comment:

The core parts of the manifest proposal are simply declarative expressions of existing kubectl commands and flags: kubectl create configmap, kubectl create secret, kubectl patch, kubectl label, kubectl annotate, --filename, --prune, --recursive, --selector.

**Pull request merged**
