### PR TITLE
fix top node output format incorrect

### PR DESCRIPTION
**Pull request by wujiangfa-xlauncher**
#1111

### CODE REVIEW

**Comment by lauchokyip** [comment]
Hi @wujiangfa-xlauncher , can you open a pull request on the main repo? 
We usually merge it to the main repo https://github.com/kubernetes/kubernetes and the mirror the code to this repo.

**Comment by wujiangfa-xlauncher** [comment]
@lauchokyip Thank you for your reply.

**Comment by wujiangfa-xlauncher** [comment]
image
What happened?

**Comment by wujiangfa-xlauncher** [comment]
@lauchokyip  I see. Thank you

**Comment by wujiangfa-xlauncher** [comment]
@lauchokyip  https://github.com/kubernetes/kubernetes/pull/105113

**Comment by lauchokyip** [comment]
Keeping track in this PR https://github.com/kubernetes/kubernetes/pull/105121

**Pull request closed without merging**
