### PR TITLE
Kubectl Book

### PR DESCRIPTION
**Pull request by pwittrock**
Initial revision of kubectl book for managing Kubernetes Applcations.

Rendered content viewable here:
- https://pwittrock-kubectl.firebaseapp.com

Tracking Bugs for how things *should* work here:
- https://github.com/kubernetes/kubectl/projects/7

### CODE REVIEW

**Comment by juanvallejo** [comment]
@pwittrock thanks for this! Is there a corresponding script that could go under `./hack/...` to render / serve the content on a browser, for example? (A small README detailing how this works / how to preview changes locally would be great)

**Comment by pwittrock** [comment]
@juanvallejo Added a CONTRIBUTING.md with instructions for building locally.

**Comment by pwittrock** [comment]
Merging this as a draft.  This approach is still being actively explored and doing a thorough review doesn't make sense right now.

High-level discussion should happen here:

https://github.com/kubernetes/kubectl/issues/556

**Pull request merged**
