### PR TITLE
Using i18n for command helps

### PR DESCRIPTION
**Pull request by jayendra13**
Fixing https://github.com/kubernetes/kubectl/issues/910

### CODE REVIEW

**Comment by eddiezane** [comment]
@jayendra13 thanks for taking this one one!

The repo setup is a bit confusing at the moment and this repo is only used for tracking kubectl issues. All PR's need to be made against the [main kubernetes repo](https://github.com/kubernetes/kubernetes). kubectl lives under [staging/src/k8s.io/kubectl](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl) there. That code is then copied here as a periodic job. This repo will eventually be the source of truth which is why it currently lives under staging while we migrate it out.

Would you kindly close this PR and reopen it there?

https://github.com/kubernetes/kubectl/blob/master/CONTRIBUTING.md

**Comment by brianpursley** [comment]
+1 to what Eddie said

But also, have you guys seen this?  https://github.com/kubernetes/kubernetes/blob/2c2ca27bfc538733c0f0ddbab7d3f2ff8707403d/translations/extract.py

Are we supposed to be running that python script?

I’m not too familiar with how kubernetes i18n works, but I wonder how broken it is because I don’t think people have been keeping it up. For example, if there is a long multi line description of a command, and one little thing changes , does that break the translations?

**Comment by jayendra13** [comment]
Ok will do that,
I will also check the k8s implementation of i18n works in the similar way.

**Pull request closed without merging**
